version: "3.9"
services:
  more-energy:
    build:
      context: ./
    container_name: more-energy
    expose:
      - ${API_SERVER_PORT}
    image: clackgot/more-energy:latest
    depends_on:
      - postgres

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nest.rule=Host(`${API_SERVER_DOMAIN}`)"
      - "traefik.http.routers.nest.tls=true"
      - "traefik.http.routers.nest.entrypoints=https"
      - "traefik.http.routers.nest.tls.certresolver=myresolver"
  postgres:
    image: postgres:alpine
    restart: always

    container_name: postgres

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      

    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # - ./domain.crt:/ssl/domain.crt
      # - ./domain.key:/ssl/domain.key
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./ssl:/ssl

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123"
    ports:
      - "16543:80"
    logging:
      driver: none
    depends_on:
      - postgres
    container_name: pgadmin

networks:
  default:
    driver: bridge
    name: network_api

volumes:
  postgres:
  nginx_config:
    name: nginx_config
