version: "3.9"
services:
  more-energy:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: more-energy
    # ports:
    #   - ${HTTP_PORT}:${HTTP_PORT}
    expose:
      - ${HTTP_PORT}
    image: clackgot/more-energy:latest
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    # environment:
    #   # - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_USER=${POSTGRES_USERNAME}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres
    # ports:
    #   - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - more-energy
    env_file:
      - .env
    command: apt update && apt-get install -y nmap && apt-get install -y nmap
     
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123"
    ports:
      - "16543:80"
    logging:
      driver: none
    depends_on:
      - postgres
    container_name: pgadmin

networks:
  default:
    driver: bridge
    name: network_api

volumes:
  postgres:
  nginx_config:
      name: nginx_config