version: "3.9"
services:
  more-energy:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: more-energy
    ports:
      - "${PORT}:${PORT}"
    image: clackgot/more-energy:latest
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      # - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    container_name: postgres
    # ports:
    #   - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123"
    ports:
      - "16543:80"
    logging:
      driver: none
    depends_on:
      - postgres
    container_name: pgadmin

networks:
  default:
    driver: bridge
    name: network_api

volumes:
  postgres:
