version: "3.9"
services:
  more-energy:
    build:
      context: ./
    container_name: more-energy
    expose:
      - ${API_SERVER_PORT}
    image: clackgot/more-energy:latest
    depends_on:
      - postgres
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.more-energy.rule=Host(`${API_SERVER_DOMAIN}`)
      - traefik.http.routers.more-energy.entrypoints=web

      - traefik.http.routers.more-energy-secure.rule=Host(`${API_SERVER_DOMAIN}`)
      - traefik.http.routers.more-energy-secure.entrypoints=web_secure


  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    container_name: postgres

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web_secure.address=:443
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123"
    ports:
      - "16543:80"
    logging:
      driver: none
    depends_on:
      - postgres
    container_name: pgadmin

networks:
  default:
    driver: bridge
    name: network_api

volumes:
  postgres: