name: set_server_envs

on: workflow_dispatch
jobs:
  backend-run:
    runs-on: ubuntu-latest
    env:
      HTTP_PORT : ${{secrets.HTTP_PORT}}
      JWT_EXPIRES : ${{secrets.JWT_EXPIRES}}
      JWT_KEY : ${{secrets.JWT_KEY}}
      POSTGRES_DATABASE : ${{secrets.POSTGRES_DATABASE}}
      POSTGRES_PASSWORD : ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_PORT : ${{secrets.POSTGRES_PORT}}
      POSTGRES_USERNAME : ${{secrets.POSTGRES_USERNAME}}
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v2

      # Установка дополнительного ПО необходимого для работа ssh-action
      - name: Установка дополнительного ПО необходимого для работа ssh-action
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client -y
      # Подключение к удаленному серверу и выполнение команд
      - name: Подключение к серверу
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          
          envs: HTTP_PORT, JWT_EXPIRES, JWT_KEY, POSTGRES_DATABASE, POSTGRES_PASSWORD, POSTGRES_PORT, POSTGRES_USERNAME
          script: ./build.sh $HTTP_PORT $JWT_EXPIRES $JWT_KEY $POSTGRES_DATABASE $POSTGRES_PASSWORD $POSTGRES_PORT $POSTGRES_USERNAME