name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3
      - name: Установка зависимостей
        run: npm ci
      - name: Тестирование приложения
        run: npm run test
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3
      - name: Установка зависимостей
        run: npm ci
      - name: Проверка синтаксиса линтером
        run: npm run lint
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3

    - name: Авторизация в DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/compose-cli-action@0.10.0
      with:
        compose-file: docker-compose.yml
        context: .
        command: push
    
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Клонирование репозитория
  #       uses: actions/checkout@v2

  #     # Установка дополнительного ПО необходимого для работа ssh-action
  #     - name: Установка дополнительного ПО необходимого для работа ssh-action
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install openssh-client -y

  #     # Подключение к удаленному серверу и выполнение команд
  #     - name: Подключение к серверу
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.REMOTE_HOST }}
  #         username: ${{ secrets.REMOTE_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         port: 22
  #         script: ls -la ~